version: '1.0'
services:
  security_jwt:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    depends_on:
      - database
    networks:
      - security_network
    ports:
      - "8181:8181"
  database:
    image: mysql:latest
    hostname: jwt_security
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "jwt@1234"
      MYSQL_DATABASE: "jwt_security"
    ports:
      - "3306:3306"
    networks:
      - security_network
networks:
  security_network:
    driver: bridge
